"""
Class that extends the Phoenix 6 SwerveDrivetrain class and implements Subsystem so it can
easily be used in command-based projects.

Generated by the 2026 Tuner X Swerve Project Generator
https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
"""

import math
from typing import Callable

from commands2 import Command, Subsystem
from commands2.sysid import SysIdRoutine
from pathplannerlib.auto import AutoBuilder
from pathplannerlib.config import PIDConstants, RobotConfig
from pathplannerlib.controller import PPHolonomicDriveController
from phoenix6 import SignalLogger, utils
from phoenix6.hardware import CANcoder, TalonFX
from phoenix6.swerve import SwerveDrivetrain, requests as swerve_requests
from wpilib import DriverStation, Notifier, RobotController
from wpimath.geometry import Rotation2d

import constants


class CommandSwerveDrivetrain(SwerveDrivetrain, Subsystem):
    _kSimLoopPeriod = 0.004  # 4 ms

    speedMod = constants.DriveConstants.fullSpeed

    # Blue alliance sees forward as 0 degrees (toward red alliance wall)
    _kBlueAlliancePerspectiveRotation = Rotation2d()
    # Red alliance sees forward as 180 degrees (toward blue alliance wall)
    _kRedAlliancePerspectiveRotation = Rotation2d.fromDegrees(180)

    def __init__(self, drivetrain_constants, *modules):
        SwerveDrivetrain.__init__(
            self,
            TalonFX,
            TalonFX,
            CANcoder,
            drivetrain_constants,
            list(modules),
        )
        Subsystem.__init__(self)

        self._m_simNotifier: Notifier | None = None
        self._m_lastSimTime = 0.0
        self._m_hasAppliedOperatorPerspective = False

        # Swerve requests to apply during SysId characterization
        self._m_translationCharacterization = swerve_requests.SysIdSwerveTranslation()
        self._m_steerCharacterization = swerve_requests.SysIdSwerveSteerGains()
        self._m_rotationCharacterization = swerve_requests.SysIdSwerveRotation()

        # SysId routine for characterizing translation. Used to find PID gains for the drive motors.
        self._m_sysIdRoutineTranslation = SysIdRoutine(
            SysIdRoutine.Config(
                rampRate=None,          # Use default ramp rate (1 V/s)
                stepVoltage=4.0,        # Reduce dynamic step voltage to 4 V to prevent brownout
                timeout=None,           # Use default timeout (10 s)
                recordState=lambda state: SignalLogger.write_string(
                    "SysIdTranslation_State", str(state)
                ),
            ),
            SysIdRoutine.Mechanism(
                lambda output: self.set_control(
                    self._m_translationCharacterization.with_volts(output)
                ),
                lambda log: None,
                self,
            ),
        )

        # SysId routine for characterizing steer. Used to find PID gains for the steer motors.
        self._m_sysIdRoutineSteer = SysIdRoutine(
            SysIdRoutine.Config(
                rampRate=None,
                stepVoltage=7.0,
                timeout=None,
                recordState=lambda state: SignalLogger.write_string(
                    "SysIdSteer_State", str(state)
                ),
            ),
            SysIdRoutine.Mechanism(
                lambda volts: self.set_control(
                    self._m_steerCharacterization.with_volts(volts)
                ),
                lambda log: None,
                self,
            ),
        )

        # SysId routine for characterizing rotation. Used to find PID gains for the
        # FieldCentricFacingAngle HeadingController.
        self._m_sysIdRoutineRotation = SysIdRoutine(
            SysIdRoutine.Config(
                # This is in radians per second², but SysId only supports "volts per second"
                rampRate=math.pi / 6,
                # This is in radians per second, but SysId only supports "volts"
                stepVoltage=math.pi,
                timeout=None,
                recordState=lambda state: SignalLogger.write_string(
                    "SysIdRotation_State", str(state)
                ),
            ),
            SysIdRoutine.Mechanism(
                lambda output: (
                    self.set_control(
                        self._m_rotationCharacterization.with_rotational_rate(output)
                    ),
                    SignalLogger.write_double("Rotational_Rate", output),
                ),
                lambda log: None,
                self,
            ),
        )

        # The SysId routine to test
        self._m_sysIdRoutineToApply = self._m_sysIdRoutineTranslation

        if utils.is_simulation():
            self._startSimThread()
        self._configureAutoBuilder()

    def _configureAutoBuilder(self):
        try:
            config = RobotConfig.fromGUISettings()
            AutoBuilder.configure(
                lambda: self.get_state().pose,
                self.reset_pose,
                lambda: self.get_state().speeds,
                lambda speeds, feedforwards: self.set_control(
                    swerve_requests.ApplyRobotSpeeds()
                    .with_speeds(speeds)
                    .with_wheel_force_feedforwards_x(feedforwards.robotRelativeForcesXNewtons())
                    .with_wheel_force_feedforwards_y(feedforwards.robotRelativeForcesYNewtons())
                ),
                PPHolonomicDriveController(
                    PIDConstants(5, 0, 0),
                    PIDConstants(5, 0, 0),
                ),
                config,
                lambda: (DriverStation.getAlliance() or DriverStation.Alliance.kBlue)
                == DriverStation.Alliance.kRed,
                self,
            )
        except Exception as e:
            DriverStation.reportError(f"Failed to load PathPlanner config: {e}", True)

    def applyRequest(self, request: Callable[[], swerve_requests.SwerveRequest]) -> Command:
        """Returns a command that applies the specified control request to this swerve drivetrain."""
        return self.run(lambda: self.set_control(request()))

    def sysIdQuasistatic(self, direction) -> Command:
        return self._m_sysIdRoutineToApply.quasistatic(direction)

    def sysIdDynamic(self, direction) -> Command:
        return self._m_sysIdRoutineToApply.dynamic(direction)

    def periodic(self):
        # Periodically try to apply the operator perspective.
        # If we haven't applied the operator perspective before, apply it regardless of DS state.
        # Otherwise only check and apply the operator perspective if the DS is disabled.
        if not self._m_hasAppliedOperatorPerspective or DriverStation.isDisabled():
            alliance = DriverStation.getAlliance()
            if alliance is not None:
                self.set_operator_perspective_forward(
                    self._kRedAlliancePerspectiveRotation
                    if alliance == DriverStation.Alliance.kRed
                    else self._kBlueAlliancePerspectiveRotation
                )
                self._m_hasAppliedOperatorPerspective = True

    def _startSimThread(self):
        self._m_lastSimTime = utils.get_current_time_seconds()

        def _run():
            current_time = utils.get_current_time_seconds()
            delta_time = current_time - self._m_lastSimTime
            self._m_lastSimTime = current_time
            self.update_sim_state(delta_time, RobotController.getBatteryVoltage())

        self._m_simNotifier = Notifier(_run)
        self._m_simNotifier.startPeriodic(self._kSimLoopPeriod)

    def add_vision_measurement(self, vision_robot_pose, timestamp_seconds, vision_measurement_std_devs=None):
        if vision_measurement_std_devs is None:
            super().add_vision_measurement(
                vision_robot_pose, utils.fpga_to_current_time(timestamp_seconds)
            )
        else:
            super().add_vision_measurement(
                vision_robot_pose,
                utils.fpga_to_current_time(timestamp_seconds),
                vision_measurement_std_devs,
            )

    def sample_pose_at(self, timestamp_seconds):
        return super().sample_pose_at(utils.fpga_to_current_time(timestamp_seconds))

    def slowSpeed(self):
        """Slows the drive train to 60%."""
        CommandSwerveDrivetrain.speedMod = constants.DriveConstants.slowSpeed

    def normalSpeed(self):
        """Normal speed (times 1)."""
        CommandSwerveDrivetrain.speedMod = constants.DriveConstants.fullSpeed

    def getSpeedMod(self) -> float:
        return CommandSwerveDrivetrain.speedMod
